config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :reservations
  resources :tutos
  resources :lists do
    resources :tasks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  belongs_to :tuto, optional: true
end

app/models/tuto.rb
class Tuto < ApplicationRecord
  has_many :tasks
  has_many_attached :photos
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :task_names,)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @lists = List.all
    @reservations = Reservation.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[edit update destroy]

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to reservations_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservations_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @reservation.destroy
    redirect_to reservations_path, status: :see_other
  end

  private

  def reservation_params
    params.require(:reservation).permit(:arrival, :departure, :comment, :user_id)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/tutos_controller.rb
class TutosController < ApplicationController
  before_action :set_tuto, only: %i[show edit update destroy]

  def index
    @tutos = Tuto.all
  end

  def show
  end

  def new
    @tuto = Tuto.new
  end

  def create
    @tuto = Tuto.new(tuto_params)
    if @tuto.save
      redirect_to tutos_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @tuto.update(tuto_params)
      if tuto_params[:photos].join.present?
        @tuto.photos.purge
        @tuto.update(photos: tuto_params[:photos])
      end
      redirect_to tuto_path(@tuto)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tuto.destroy
    redirect_to tutos_path, status: :see_other
  end

  private

  def set_tuto
    @tuto = Tuto.find(params[:id])
  end

  def tuto_params
    params.require(:tuto).permit(:name, :description, :url, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taupi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
      <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.input :task_names, label: "Tâches" %>
    <%= f.submit "Soumettre", class: "btn btn-primary" %>
  <% end %>

app/views/lists/edit.html.erb
<div class="container w-50 mt-5">
  <h1>Modifier Liste</h1>

  <%= render "form", list: @list %>

  <%= link_to "Annuler", lists_path %>
</div>

app/views/lists/index.html.erb
<div class="container w-50 mt-5">
  <div class="d-flex justify-content-center mb-3"><h1>Listes</h1></div>


  <% @lists.each do |list| %>
    <div class="card flex-md-row mb-2 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <h5><%= link_to list.name, list_path(list) %></h5>
        <p><%= list.task_names %></p>
        <ul>
          <% list.tasks.each do |task| %>
            <li><%= task.name %></li>
          <% end %>
        </ul>
        <%= link_to "Edit", edit_list_path(list), class: "btn btn-primary" %>
        <br>
        <%= link_to "Supprimer", list_path(list), class: "btn btn-primary", data: { turbo_method: :delete, turbo_confirm: "Voulez-vous supprimer la liste définitivement ?" } %>
      </div>
    </div>
  <% end %>

  <%= link_to "Nouvelle liste", new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<div class="container w-50 mt-5">
  <h1>Nouvelle Liste</h1>

  <%= render "form", list: @list %>

  <%= link_to "Annuler", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container w-50 mt-5">
  <div class="d-flex justify-content-center mb-3"><h1><%= @list.name %></h1></div>
  <p><%= @list.task_names %></p>

  <ul>
    <% @list.tasks.each do |task| %>
      <li><%= task.name %></li>
    <% end %>
  </ul>

</div>

app/views/pages/home.html.erb
<div class="background pt-0">

<div class="container mt-4 ">
  <h1>Bienvenue à la <strong>Taupinière</strong></h1>
  <p>Lieu de villégiature pour la famille Mahoudeau</p>

    <div class="card d-sm-flex mt-2 mb-4 box-shadow ">
    <div class="mt-2 mx-2"><h5><strong>Réservations</strong></h5></div>
      <div class="d-flex flex-row mx-3 mb-3">

          <% @reservations.each do |reservation| %>
            <div class="card flex-md-row m-3 box-shadow ">
              <div class="card-body d-flex flex-column align-items-start">
                <p><strong>Date arrivée :</strong> <%= reservation.arrival %></p>
                <p><strong>Date départ :</strong> <%= reservation.departure %></p>
                <p><strong>Qui :</strong> <%= reservation.user.email%></p>
                <p><strong>Commentaire :</strong> <%= reservation.comment %></p>
              </div>
            </div>
          <% end %>

      </div>
    </div>

    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <h5><strong>Listes en cours</strong></h5>
        <ul>
          <% @lists.each do |list| %>
            <li><%= link_to list.name, list_path(list) %></li>
          <% end %>
        </ul>
      </div>
    </div>

   <%= link_to "Réservations", reservations_path, class: "btn btn-primary" %>
   <%= link_to "Listes", lists_path, class: "btn btn-primary" %>
   <%= link_to "Tutos", tutos_path, class: "btn btn-primary"  %>
</div>
</div>

app/views/reservations/_form.html.erb
  <%= simple_form_for(@reservation) do |f| %>
    <%= f.input :arrival, required: true,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :departure, required: true,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :comment %>
    <%= f.submit "Soumettre", class: "btn btn-primary" %>
  <% end %>

app/views/reservations/edit.html.erb
<div class="container w-50 mt-5">
  <h1>Modification Réservation</h1>

  <%= render "form", reservation: @reservation %>

  <%= link_to "Annuler", reservations_path %>
</div>

app/views/reservations/index.html.erb
<div class="container w-50 mt-5">
  <h1>Réservations</h1>

  <% @reservations.each do |reservation| %>
    <div class="card flex-md-row mb-2 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <p><strong>Date arrivée :</strong> <%= reservation.arrival %></p>
        <p><strong>Date départ :</strong> <%= reservation.departure %></p>
        <p><strong>Qui :</strong> <%= reservation.user.email%></p>
        <p><strong>Commentaire :</strong> <%= reservation.comment %></p>
        <%= link_to "Edit", edit_reservation_path(reservation), class: "btn btn-primary" %>
        <br>
        <%= link_to "Supprimer", reservation_path(reservation), class: "btn btn-primary", data: { turbo_method: :delete, turbo_confirm: "Voulez-vous supprimer la réservation définitivement ?" } %>
      </div>
    </div>
  <% end %>

  <%= link_to "Nouvelle réservation", new_reservation_path, class: "btn btn-primary" %>
</div>

app/views/reservations/new.html.erb
<div class="container w-50 mt-5">
  <h1>Nouvelle Réservation</h1>

  <%= render "form", reservation: @reservation %>

  <%= link_to "Annuler", reservations_path %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to(root_path, class: "navbar-brand") do %>
      <%= image_tag "maison_icone.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "bakun.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tutos/_form.html.erb
<%= simple_form_for(@tuto) do |f| %>
  <%= f.input :name, required: true %>
  <%= f.input :description, required: true %>
  <%= f.input :url %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Soumettre", class: "btn btn-primary" %>
<% end %>

app/views/tutos/edit.html.erb
<div class="container w-50 mt-5">
  <h1><strong> Modification Tuto </strong></h1>

  <%= render "form", tuto: @tuto %>
  <%= link_to "Annuler", tutos_path %>

</div>

app/views/tutos/index.html.erb
<div class="container w-50 mt-5">
  <h1>Tutos</h1>

  <ul>
    <% @tutos.each do |tuto| %>
        <li><%= link_to tuto.name, tuto_path(tuto) %></li>
    <% end %>
  </ul>

  <%= link_to "Nouveau Tuto", new_tuto_path, class: "btn btn-primary" %>
</div>

app/views/tutos/new.html.erb
<div class="tutos mt-5">
<h1><strong> Nouveau Tuto </strong></h1>

<%= render "form", tuto: @tuto %>
<%= link_to "Annuler", tutos_path %>

</div>

app/views/tutos/show.html.erb
<div class="container w-50 mt-5">

  <h1><%= @tuto.name %></h1>
    <p><strong>Instruction :</strong> <%= @tuto.description %></p>
    <p> <% if @tuto.url.present? %> <strong>URL :</strong> <%= link_to @tuto.url, @tuto.url %><% end %></p>
		<% @tuto.photos.each do |photo| %>
		  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
		<% end %>
</div>

<div class="container w-50 mt-5">
    <%= link_to "Editer Tutos", edit_tuto_path(@tuto), class: "btn btn-primary" %>
    <%= link_to "Supprimer le tuto", tuto_path(@tuto), class: "btn btn-primary",  data: { turbo_method: :delete, turbo_confirm: "Voulez-vous supprimer le tuto définitivement ?" } %>
  <br>
    <%= link_to "Retour Tutos", tutos_path %>
</div>